org.gradle.jvmargs=-Xmx4G
org.gradle.workers.max=4
org.gradle.parallel=true

# Mod Properties
mod.version=0.1.0-SNAPSHOT
mod.group=dev.chililisoup
mod.id=modularsynths
mod.name=Modular Synths
mod.authors=chililisoup
mod.description=Modular synths rewrite #2 hopefully this one makes it
mod.homepage=https://modrinth.com/mod/modularsynths
mod.sources=https://github.com/chililisoup/ModularSynths
mod.issues=https://github.com/chililisoup/ModularSynths/issues
mod.license=ARR

# Dependencies
deps.minecraft=26.1.2
deps.minecraft_range=~26.1
deps.fabric_loader=0.19.2
deps.fabric_api=0.148.0+26.1.2
